export const destinations = [
  { id: "malibu", name: "Malibu, CA", image: "/dest-beach.jpg", pairs: 24, tag: "Beach" },
  { id: "aspen", name: "Aspen, CO", image: "/dest-mountain.jpg", pairs: 18, tag: "Mountain" },
  { id: "nashville", name: "Nashville, TN", image: "/dest-city.jpg", pairs: 31, tag: "City" },
];

export const featuredPairs = [
  {
    id: "pair-1",
    badge: "Trending" as const,
    separatePrice: 710,
    carMatchReason: "PCH driving demands presence. The GLE's air suspension soaks up the Pacific Coast Highway curves while fitting 4 guests and golf bags. Climate control makes the beach-to-villa commute effortless.",
    stay: {
      name: "Oceanfront Villa",
      location: "Malibu, CA",
      image: "/stay-villa1.jpg",
      gallery: ["/stay-villa1.jpg", "/stay-villa2.jpg", "/stay-villa6.jpg", "/stay-miami.jpg"],
      price: 480,
      rating: 4.9,
      reviews: 128,
      beds: 4,
      baths: 3,
      sqft: 3200,
      yearBuilt: 2019,
      tags: ["Private Pool", "Ocean View", "Hot Tub", "Private Beach"],
      description: "A 3,200 sq ft Mediterranean villa with a floodlit pool terrace, hammock garden, and tropical landscaping — lit beautifully at night. Two levels of glass and balconies look over the pool and gardens. Outdoor lounge, outdoor shower, and a chef's kitchen designed for groups. The Mercedes GLE sits in the covered parking — perfect for the PCH drive into Santa Monica.",
      amenities: ["Infinity Pool", "Chef's Kitchen", "Home Theater", "Beach Access", "Outdoor Shower", "Fire Pit", "Smart Home", "Sonos Audio"],
    },
    car: {
      name: "Mercedes GLE 450",
      brand: "Mercedes-Benz",
      year: 2024,
      type: "Luxury SUV",
      image: "/car-mercedes.jpg",
      price: 115,
      mileage: "Unlimited",
      engine: "3.0L Turbocharged V6 · 362 hp",
      transmission: "9-Speed Automatic",
      features: ["Burmester Audio", "Heated Seats", "360° Camera", "Night Vision Assist", "GPS Navigation", "MBUX Infotainment"],
      color: "Obsidian Black",
      seats: 5,
    },
    totalNights: 5,
    totalDays: 5,
  },
  {
    id: "pair-2",
    badge: "Top Pick" as const,
    separatePrice: 450,
    carMatchReason: "Snow tires installed. Quadra-Trac 4WD on mountain roads. The Grand Cherokee handles Aspen's icy switchbacks the way it was built to — and fits ski bags, poles, and four people without compromise.",
    stay: {
      name: "Alpine Ridge Cabin",
      location: "Aspen, CO",
      image: "/stay-villa3.jpg",
      gallery: ["/stay-villa3.jpg", "/stay-villa1.jpg", "/stay-villa6.jpg", "/stay-nashville.jpg"],
      price: 320,
      rating: 4.8,
      reviews: 94,
      beds: 3,
      baths: 2,
      sqft: 2100,
      yearBuilt: 2016,
      tags: ["Hot Tub", "Mountain View", "Fireplace", "Ski-In/Ski-Out"],
      description: "A handcrafted log-and-glass chalet sitting at 9,200 ft elevation with direct ski-in/ski-out access to Aspen Highlands. Vaulted ceilings with exposed timber beams, a dual-sided stone fireplace, and an outdoor soaking tub surrounded by 270° mountain panoramas. Sleeps 6, equipped with a full wet bar and game room.",
      amenities: ["Ski Storage", "Outdoor Hot Tub", "Wood-Burning Fireplace", "Wet Bar", "Game Room", "Snowshoe Rack", "Smart Thermostat", "Covered Deck"],
    },
    car: {
      name: "Jeep Grand Cherokee",
      brand: "Jeep",
      year: 2024,
      type: "4WD SUV",
      image: "/car-jeep.jpg",
      price: 89,
      mileage: "Unlimited",
      engine: "3.6L Pentastar V6 · 293 hp",
      transmission: "8-Speed Automatic",
      features: ["Quadra-Trac 4WD", "Snow Tires Installed", "Heated Seats", "Apple CarPlay", "Tow Package", "Rear Cam"],
      color: "Granite Crystal",
      seats: 5,
    },
    totalNights: 4,
    totalDays: 4,
  },
  {
    id: "pair-3",
    badge: "New" as const,
    separatePrice: 295,
    carMatchReason: "The building has Tesla charging in the garage. Autopilot on I-40. And pulling up to Broadway in a Model 3 is exactly the right energy for Nashville — city car, clean, quiet, no gas stops.",
    stay: {
      name: "Gulch Glass Loft",
      location: "Nashville, TN",
      image: "/stay-nashville.jpg",
      gallery: ["/stay-nashville.jpg", "/stay-villa1.jpg", "/stay-villa6.jpg", "/stay-villa2.jpg"],
      price: 195,
      rating: 4.7,
      reviews: 212,
      beds: 2,
      baths: 1,
      sqft: 1400,
      yearBuilt: 2021,
      tags: ["Rooftop Access", "City View", "Gym", "Walkable"],
      description: "A 10th-floor glass-walled loft in Nashville's Gulch neighborhood with panoramic views of the downtown skyline and Cumberland River. Floor-to-ceiling windows flood the open-plan living space with natural light. Steps from Broadway's live music scene — walk to Honky Tonk Highway, hot chicken spots, and the best cocktail bars in town.",
      amenities: ["Rooftop Terrace", "Fitness Center", "Concierge", "Parking", "Bike Storage", "Package Locker", "Fast WiFi", "Pet Friendly"],
    },
    car: {
      name: "Tesla Model 3",
      brand: "Tesla",
      year: 2024,
      type: "Electric Sedan",
      image: "/car-tesla.jpg",
      price: 75,
      mileage: "Unlimited",
      engine: "Dual Motor AWD · 358 hp · 358mi range",
      transmission: "Single-Speed Direct Drive",
      features: ["Full Self-Driving", "Autopilot", "15\" Touchscreen", "Premium Audio", "USB-C", "Over-Air Updates"],
      color: "Midnight Silver",
      seats: 5,
    },
    totalNights: 3,
    totalDays: 3,
  },
];

export const stats = [
  { value: "50K+", label: "Pairs Booked" },
  { value: "120+", label: "Destinations" },
  { value: "4.9★", label: "Avg Rating" },
  { value: "100%", label: "Timing Guaranteed" },
];

// Extended pairs set for search + stays pages
export const allPairs = [
  ...featuredPairs,
  {
    id: "pair-4",
    badge: "Deal" as const,
    separatePrice: 490,
    carMatchReason: "Top down on the Biscayne Causeway with a 495hp V8. The Corvette is the only logical choice for South Beach — it parks in the motor court, turns every red light into a moment, and matches the villa's energy entirely.",
    hotel: { id: "h4", name: "Star Island Villa", location: "Miami Beach, FL", pricePerNight: 290, rating: 4.8 },
    stay: {
      name: "Star Island Villa",
      location: "Miami Beach, FL",
      image: "/stay-miami.jpg",
      gallery: ["/stay-miami.jpg", "/stay-villa2.jpg", "/stay-villa1.jpg", "/stay-villa6.jpg"],
      price: 290,
      rating: 4.8,
      reviews: 185,
      beds: 4,
      baths: 3,
      sqft: 3600,
      yearBuilt: 2022,
      tags: ["Private Pool", "Palm Garden", "Open-Plan", "Putting Green"],
      description: "A flat-roofed modernist estate on Star Island with a resort-scale pool terrace, putting green, and lush palm gardens. Travertine throughout, custom outdoor kitchen, and a sun deck with Italian umbrellas. 10 minutes to South Beach, 5 to the Design District. Perfect base for Corvette top-down driving on Biscayne Causeway.",
      amenities: ["Private Pool", "Putting Green", "Outdoor Kitchen", "Private Garden", "Cabana Seating", "EV Charger", "Smart Home", "Valet Driveway"],
    },
    car: {
      name: "Chevrolet Corvette C8",
      brand: "Chevrolet",
      year: 2024,
      type: "Sports Convertible",
      image: "/car-corvette.jpg",
      price: 145,
      mileage: "250 mi/day",
      engine: "6.2L LT2 V8 · 495 hp",
      transmission: "8-Speed Dual-Clutch",
      features: ["Convertible Top", "Magnetic Ride Control", "Head-Up Display", "Bose Audio", "Sport Mode", "Launch Control"],
      color: "Torch Red",
      seats: 2,
    },
    totalNights: 4,
    totalDays: 4,
  },
  {
    id: "pair-5",
    badge: "Trending" as const,
    separatePrice: 780,
    carMatchReason: "Executive level, Tribeca to JFK in 28 minutes. The BMW 7 Series chauffeur package means you sit in the back with B&W audio, massage seats, and a phone charger — the penthouse starts the moment you leave it.",
    hotel: { id: "h5", name: "Manhattan Tower Penthouse", location: "New York, NY", pricePerNight: 520, rating: 4.9 },
    stay: {
      name: "Manhattan Tower Penthouse",
      location: "Tribeca, New York",
      image: "/stay-manhattan.jpg",
      gallery: ["/stay-manhattan.jpg", "/stay-nashville.jpg", "/stay-villa1.jpg", "/stay-villa6.jpg"],
      price: 520,
      rating: 4.9,
      reviews: 340,
      beds: 3,
      baths: 2,
      sqft: 2600,
      yearBuilt: 2018,
      tags: ["Skyline View", "Concierge", "Downtown Views", "Floor-to-Ceiling Glass"],
      description: "A high-floor penthouse dining room and living space wrapped in floor-to-ceiling glass, framing the One World Trade and Manhattan skyline at night — among the most dramatic views available in any private rental. Italian marble, custom chandelier, and a layout designed for entertaining. BMW in the garage below, city is your backyard.",
      amenities: ["Private Terrace", "Rooftop Pool", "24/7 Concierge", "Skyline Views", "Grand Piano", "Home Gym", "Wine Cellar", "Smart Home"],
    },
    car: {
      name: "BMW 7 Series",
      brand: "BMW",
      year: 2024,
      type: "Executive Luxury",
      image: "/car-bmw.jpg",
      price: 200,
      mileage: "Unlimited",
      engine: "3.0L TwinPower Turbo · 375 hp",
      transmission: "8-Speed Sport Automatic",
      features: ["Chauffeur Package", "Executive Lounge Seating", "Bowers & Wilkins Audio", "Massage Seats", "Crystal Glass Controls", "Rear Entertainment"],
      color: "Frozen Black",
      seats: 5,
    },
    totalNights: 3,
    totalDays: 3,
  },
  {
    id: "pair-6",
    badge: "Top Pick" as const,
    separatePrice: 565,
    carMatchReason: "Mulholland Drive was made for a Range Rover Sport. Air suspension on switchbacks, Terrain Response on unpaved canyon paths, and it fits in the villa's motor court like it was ordered for the shoot.",
    hotel: { id: "h6", name: "Cliffside Infinity Villa", location: "Malibu, CA", pricePerNight: 380, rating: 4.7 },
    stay: {
      name: "Cliffside Infinity Villa",
      location: "Pacific Palisades, CA",
      image: "/stay-villa6.jpg",
      gallery: ["/stay-villa6.jpg", "/stay-villa1.jpg", "/stay-villa2.jpg", "/stay-villa3.jpg"],
      price: 380,
      rating: 4.7,
      reviews: 97,
      beds: 4,
      baths: 3,
      sqft: 3100,
      yearBuilt: 2020,
      tags: ["Infinity Pool", "Mountain View", "Sunset Terrace", "Glass Walls"],
      description: "A dramatic cliffside villa in Pacific Palisades with a glass-edged infinity pool that disappears into mountain and ocean views at sunset. Concrete pillar architecture, floor-to-ceiling sliding glass doors, and a terraced stone patio. The Range Rover is parked in the motor court — it was made for Mulholland Drive at golden hour.",
      amenities: ["Infinity Pool", "Sunset Terrace", "Outdoor Lounge", "Glass Walls", "Outdoor Shower", "BBQ Area", "Smart Home", "EV Charger"],
    },
    car: {
      name: "Range Rover Sport",
      brand: "Land Rover",
      year: 2024,
      type: "Luxury SUV",
      image: "/car-rover.jpg",
      price: 130,
      mileage: "Unlimited",
      engine: "3.0L P360 MHEV · 355 hp",
      transmission: "8-Speed ZF Automatic",
      features: ["Air Suspension", "Terrain Response 2", "Meridian Audio", "Panoramic Roof", "Heated/Cooled Seats", "Head-Up Display"],
      color: "Silicon Silver",
      seats: 5,
    },
    totalNights: 5,
    totalDays: 5,
  },
];

// Add hotel field to featured pairs for stays page compatibility
allPairs[0] = { ...allPairs[0], hotel: { id: "h1", name: allPairs[0].stay.name, location: allPairs[0].stay.location, pricePerNight: allPairs[0].stay.price, rating: allPairs[0].stay.rating } } as any;
allPairs[1] = { ...allPairs[1], hotel: { id: "h2", name: allPairs[1].stay.name, location: allPairs[1].stay.location, pricePerNight: allPairs[1].stay.price, rating: allPairs[1].stay.rating } } as any;
allPairs[2] = { ...allPairs[2], hotel: { id: "h3", name: allPairs[2].stay.name, location: allPairs[2].stay.location, pricePerNight: allPairs[2].stay.price, rating: allPairs[2].stay.rating } } as any;

export const howItWorks = [
  { step: "01", title: "Search Once", desc: "Enter your destination and dates. One search covers both your stay and your car." },
  { step: "02", title: "We Match the Timing", desc: "Our engine checks check-in times against car pickup windows — only showing pairs where logistics actually work." },
  { step: "03", title: "Book Together", desc: "One booking, one confirmation, zero coordination headache between Vrbo, Expedia, and Discover Cars." },
];

export const testimonials = [
  {
    quote: "I've booked 40+ trips and this is genuinely the first time I didn't have to spend an hour cross-checking hotel check-in vs. car pickup times. Game changer.",
    name: "Rachel T.",
    role: "Frequent traveler · Miami",
    avatar: "R",
    rating: 5,
  },
  {
    quote: "We landed in Aspen, the Jeep was at the same address as our cabin check-in. I thought there was a mistake. There wasn't. That's just how Pairlo works.",
    name: "Marcus & Jen W.",
    role: "Honeymoon trip · Aspen",
    avatar: "M",
    rating: 5,
  },
  {
    quote: "Saved $340 vs booking separately on Expedia + Hertz. The pair pricing is real. Will never book any other way.",
    name: "Derek O.",
    role: "Business traveler · NYC",
    avatar: "D",
    rating: 5,
  },
];

// ── ADDITIONAL PAIRS (for richer search experience) ─────────────────────
const extraPairs: typeof allPairs = [
  {
    id: "pair-7",
    badge: "Deal" as const,
    separatePrice: 410,
    carMatchReason: "Chicago's lakefront is best explored in a Tesla. Silent, smooth, and the Autopilot handles Lake Shore Drive traffic while you watch the skyline roll by.",
    hotel: { id: "h7", name: "Lakefront Penthouse Loft", location: "Chicago, IL", pricePerNight: 275, rating: 4.7 } as any,
    stay: {
      name: "Lakefront Penthouse Loft",
      location: "Chicago, IL",
      image: "/stay-nashville.jpg",
      gallery: ["/stay-nashville.jpg", "/stay-manhattan.jpg", "/stay-villa1.jpg"],
      price: 275,
      rating: 4.7,
      reviews: 163,
      beds: 2,
      baths: 2,
      sqft: 1800,
      yearBuilt: 2020,
      tags: ["Lake View", "Rooftop", "City Center", "Modern"],
      description: "A sleek 18th-floor loft in the heart of Chicago with panoramic views of Lake Michigan and the city skyline. Steps from Millennium Park, the Art Institute, and the best deep-dish in the city. Tesla in the garage for effortless lakefront drives.",
      amenities: ["Lake View", "Rooftop Terrace", "Fast WiFi", "Gym Access", "Concierge", "Underground Parking"],
    },
    car: {
      name: "Tesla Model Y",
      brand: "Tesla",
      year: 2024,
      type: "Electric SUV",
      image: "/car-tesla.jpg",
      price: 82,
      mileage: "Unlimited",
      engine: "Dual Motor AWD · 384 hp · 330mi range",
      transmission: "Single-Speed Direct Drive",
      features: ["Autopilot", "Panoramic Roof", "Heated Seats", "15\" Screen", "Premium Audio", "FSD"],
      color: "Pearl White",
      seats: 5,
    },
    totalNights: 3,
    totalDays: 3,
  },
  {
    id: "pair-8",
    badge: "Top Pick" as const,
    separatePrice: 620,
    carMatchReason: "Scottsdale's desert roads and resort driveways were designed for a Porsche Cayenne. Valet pulls up, heads turn, Camelback Mountain at sunset looks even better through the panoramic roof.",
    hotel: { id: "h8", name: "Desert Rose Estate", location: "Scottsdale, AZ", pricePerNight: 390, rating: 4.9 } as any,
    stay: {
      name: "Desert Rose Estate",
      location: "Scottsdale, AZ",
      image: "/stay-villa2.jpg",
      gallery: ["/stay-villa2.jpg", "/stay-villa6.jpg", "/stay-villa1.jpg"],
      price: 390,
      rating: 4.9,
      reviews: 201,
      beds: 5,
      baths: 4,
      sqft: 4200,
      yearBuilt: 2021,
      tags: ["Pool", "Desert Views", "Private Tennis", "Golf Cart"],
      description: "A sprawling Sonoran desert estate with mountain views, a resort-scale pool, private tennis court, and a fire pit terrace for unforgettable Arizona sunsets. Porsche Cayenne in the motor court — built for desert roads and resort drives.",
      amenities: ["Resort Pool", "Tennis Court", "Fire Pit", "Outdoor Kitchen", "Golf Cart Included", "Smart Home", "Wine Cellar", "Putting Green"],
    },
    car: {
      name: "Porsche Cayenne",
      brand: "Porsche",
      year: 2024,
      type: "Luxury SUV",
      image: "/car-rover.jpg",
      price: 168,
      mileage: "Unlimited",
      engine: "3.0L Turbo V6 · 348 hp",
      transmission: "8-Speed Tiptronic",
      features: ["Air Suspension", "PASM", "Bose Surround", "Panoramic Roof", "Sport Chrono", "Matrix LED"],
      color: "Jet Black",
      seats: 5,
    },
    totalNights: 4,
    totalDays: 4,
  },
  {
    id: "pair-9",
    badge: "New" as const,
    separatePrice: 520,
    carMatchReason: "San Francisco's hills and fog demand a Range Rover Velar. Effortlessly handles steep inclines, looks right at home in Pacific Heights, and the panoramic roof makes the Bay Bridge even more cinematic.",
    hotel: { id: "h9", name: "Pacific Heights Townhouse", location: "San Francisco, CA", pricePerNight: 340, rating: 4.8 } as any,
    stay: {
      name: "Pacific Heights Townhouse",
      location: "San Francisco, CA",
      image: "/stay-villa3.jpg",
      gallery: ["/stay-villa3.jpg", "/stay-villa1.jpg", "/stay-nashville.jpg"],
      price: 340,
      rating: 4.8,
      reviews: 88,
      beds: 3,
      baths: 2,
      sqft: 2400,
      yearBuilt: 2018,
      tags: ["Bay Views", "Victorian Charm", "Garden", "Walkable"],
      description: "A beautifully restored Victorian townhouse in Pacific Heights with partial Bay views, a private garden, and period details throughout. Walk to the Ferry Building, Golden Gate Park, and the best dim sum in the Mission. Range Rover Velar for the hills.",
      amenities: ["Bay Views", "Private Garden", "Fireplace", "Gourmet Kitchen", "Bike Storage", "Smart Home", "EV Charging"],
    },
    car: {
      name: "Range Rover Velar",
      brand: "Land Rover",
      year: 2024,
      type: "Luxury SUV",
      image: "/car-rover.jpg",
      price: 145,
      mileage: "Unlimited",
      engine: "2.0L Turbocharged · 296 hp",
      transmission: "9-Speed Automatic",
      features: ["Air Suspension", "Pivi Pro", "Meridian Sound", "Panoramic Roof", "360° Camera", "Touch Pro Duo"],
      color: "Fuji White",
      seats: 5,
    },
    totalNights: 4,
    totalDays: 4,
  },
];

// Merge extra pairs
allPairs.push(...extraPairs);

// Map pin data for search page
export const mapPins = [
  { id: "pair-1", label: "Malibu", lat: 34.0259, lng: -118.7798, price: 595, top: "62%", left: "8%" },
  { id: "pair-2", label: "Aspen", lat: 39.1911, lng: -106.8175, price: 409, top: "38%", left: "30%" },
  { id: "pair-3", label: "Nashville", lat: 36.1627, lng: -86.7816, price: 270, top: "45%", left: "60%" },
  { id: "pair-4", label: "Miami", lat: 25.7617, lng: -80.1918, price: 435, top: "75%", left: "67%" },
  { id: "pair-5", label: "New York", lat: 40.7128, lng: -74.006, price: 720, top: "28%", left: "78%" },
  { id: "pair-6", label: "Los Angeles", lat: 34.0522, lng: -118.2437, price: 510, top: "55%", left: "10%" },
  { id: "pair-7", label: "Chicago", lat: 41.8781, lng: -87.6298, price: 357, top: "32%", left: "62%" },
  { id: "pair-8", label: "Scottsdale", lat: 33.4942, lng: -111.9261, price: 524, top: "58%", left: "22%" },
  { id: "pair-9", label: "San Francisco", lat: 37.7749, lng: -122.4194, price: 485, top: "48%", left: "5%" },
];
